TABLE_SCHEMAS = {
    "car_dataset.new_car": [
        {"name": "new_car_id", "type": "INT64", "mode": "REQUIRED"},
        {"name": "external_id", "type": "STRING", "mode": "NULLABLE"},
        {"name": "listing_url", "type": "STRING", "mode": "NULLABLE"},
        {"name": "car_model", "type": "STRING", "mode": "NULLABLE"},
        {"name": "brand", "type": "STRING", "mode": "NULLABLE"},
        {"name": "color", "type": "STRING", "mode": "NULLABLE"},
        {"name": "fuel_type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "price", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "depreciation_per_year", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "registration_date", "type": "DATE", "mode": "NULLABLE"},
        {"name": "coe_left", "type": "STRING", "mode": "NULLABLE"},
        {"name": "mileage", "type": "INT64", "mode": "NULLABLE"},
        {"name": "manufactured_year", "type": "INT64", "mode": "NULLABLE"},
        {"name": "road_tax_per_year", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "transmission", "type": "STRING", "mode": "NULLABLE"},
        {"name": "dereg_value", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "omv", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "coe_value", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "arf", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "engine_capacity_cc", "type": "INT64", "mode": "NULLABLE"},
        {"name": "power", "type": "INT64", "mode": "NULLABLE"},
        {"name": "curb_weight", "type": "INT64", "mode": "NULLABLE"},
        {"name": "no_of_owners", "type": "INT64", "mode": "NULLABLE"},
        {"name": "vehicle_type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "scraped_datetime", "type": "DATETIME", "mode": "NULLABLE"},
        {"name": "posted_datetime", "type": "DATETIME", "mode": "NULLABLE"},
        {"name": "updated_datetime", "type": "DATETIME", "mode": "NULLABLE"},
        {"name": "active", "type": "BOOLEAN", "mode": "NULLABLE"},
    ],
    
    "car_dataset.used_car": [
        {"name": "used_car_id", "type": "INT64", "mode": "REQUIRED"},
        {"name": "external_id", "type": "STRING", "mode": "NULLABLE"},
        {"name": "listing_url", "type": "STRING", "mode": "NULLABLE"},
        {"name": "car_model", "type": "STRING", "mode": "NULLABLE"},
        {"name": "brand", "type": "STRING", "mode": "NULLABLE"},
        {"name": "color", "type": "STRING", "mode": "NULLABLE"},
        {"name": "fuel_type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "price", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "depreciation_per_year", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "registration_date", "type": "DATE", "mode": "NULLABLE"},
        {"name": "coe_left", "type": "STRING", "mode": "NULLABLE"},
        {"name": "mileage", "type": "INT64", "mode": "NULLABLE"},
        {"name": "manufactured_year", "type": "INT64", "mode": "NULLABLE"},
        {"name": "road_tax_per_year", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "transmission", "type": "STRING", "mode": "NULLABLE"},
        {"name": "dereg_value", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "omv", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "coe_value", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "arf", "type": "NUMERIC", "mode": "NULLABLE"},
        {"name": "engine_capacity_cc", "type": "INT64", "mode": "NULLABLE"},
        {"name": "power", "type": "INT64", "mode": "NULLABLE"},
        {"name": "curb_weight", "type": "INT64", "mode": "NULLABLE"},
        {"name": "no_of_owners", "type": "INT64", "mode": "NULLABLE"},
        {"name": "vehicle_type", "type": "STRING", "mode": "NULLABLE"},
        {"name": "scraped_datetime", "type": "DATETIME", "mode": "NULLABLE"},
        {"name": "posted_datetime", "type": "DATETIME", "mode": "NULLABLE"},
        {"name": "updated_datetime", "type": "DATETIME", "mode": "NULLABLE"},
        {"name": "active", "type": "BOOLEAN", "mode": "NULLABLE"},
    ],

    "car_dataset.coe_price": [
        {"name": "coe_id", "type": "INT64", "mode": "REQUIRED"},
        {"name": "month", "type": "DATE", "mode": "NULLABLE"},
        {"name": "bidding_no", "type": "INT64", "mode": "NULLABLE"},
        {"name": "vehicle_class", "type": "STRING", "mode": "NULLABLE"},
        {"name": "quota", "type": "INT64", "mode": "NULLABLE"},
        {"name": "bids_success", "type": "INT64", "mode": "NULLABLE"},
        {"name": "bids_received", "type": "INT64", "mode": "NULLABLE"},
        {"name": "premium", "type": "INT64", "mode": "NULLABLE"},
        {"name": "timestamp", "type": "DATETIME", "mode": "NULLABLE"},
    ],
}
